"""Add new params count and sqrt_var

Revision ID: dfbe07efa0ca
Revises: 256814bdff86
Create Date: 2024-05-25 14:45:28.846265

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dfbe07efa0ca'
down_revision = '256814bdff86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.drop_column('gender')
        batch_op.drop_column('score')

    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scores_count', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('sqrt_var', sa.Float(), nullable=True))
        batch_op.drop_column('scores_before_percent')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scores_before_percent', mysql.FLOAT(), nullable=True))
        batch_op.drop_column('sqrt_var')
        batch_op.drop_column('scores_count')

    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('gender', mysql.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
